name: amilys embyserver latest version

on:
    workflow_dispatch:
    schedule:
        - cron: '0 3 */3 * *'
    push:
        branches:
            - master
        paths:
            - ".github/workflows/amilys_embyserver_latest_version.yml"

jobs:
  get:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      -
        name: Get Version
        run: |
            docker run --entrypoint cp -v ${PWD}/emby:/data amilys/embyserver:latest /system/EmbyServer.deps.json /data
            LATEST_VERSION=$(grep "EmbyServer" emby/EmbyServer.deps.json | head -n 1 | sed -n 's|.*EmbyServer/\(.*\)":.*|\1|p')
            sed -i "1,40s|amilys_embyserver_latest_version=.*|amilys_embyserver_latest_version=${LATEST_VERSION}|" all_in_one.sh

      - 
        uses: stefanzweifel/git-auto-commit-action@be823a7e51f116fecebc222b8307716921375992
        with:
            commit_message: 'chore: update amilys embyserver latest version'
            branch: master
            file_pattern: 'all_in_one.sh'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
